#define DEFAULT_PC 0x100
#define DEFAULT_SP 0xFFFE
#define DEFAULT_AF 0x1B0
#define DEFAULT_BC 0x13
#define DEFAULT_DE 0xD8
#define DEFAULT_HL 0x14D

#define INSTRUCTION_COUNT 256
#define CB_INSTRUCTION_COUNT 256

#define FLAG_ZERO 'Z'
#define FLAG_SUBTRACT 'N'
#define FLAG_HALFCARRY 'H'
#define FLAG_CARRY 'C'

#define INT_VBLANK 0x40
#define INT_LCD_STAT 0x48
#define INT_TIMER 0x50
#define INT_SERIAL 0x58
#define INT_JOYPAD 0x60 

typedef struct gbc_instruction {
    char *disassembly;
    char length;
    char clocks;
    char increment_PC;
    char signed_operand;
    void *execute;
} gbc_instruction;

void init_cpu(gbc_cpu *);
gbc_instruction find_instr(const unsigned char, gbc_system *);

static void execute_instr(gbc_instruction, gbc_system *);
static gbc_instruction get_curr_instr(gbc_system *);

void simulate_cpu(gbc_system *);
void cpu_do_clock(gbc_system *);

static void set_flag(const char, const unsigned char, unsigned char *);
static char get_flag(const char, const unsigned char);

static void stack_push(const unsigned char, gbc_ram *, unsigned short *);
static unsigned char stack_pop(gbc_ram *, unsigned short *);

void check_interrupt(gbc_system *);
static void service_interrupt(gbc_system *, const unsigned char);

// CPU Instructions
static void op_ld_a_d(gbc_system *);
static void op_nop(gbc_system *);
static void op_ld_bcp_a(gbc_system *);
static void op_inc_bc(gbc_system *);
static void op_inc_b(gbc_system *);
static void op_dec_b(gbc_system *);
static void op_ld_b_d8(gbc_system *, unsigned char);
static void op_rlca(gbc_system *);
static void op_ld_a16p_sp(gbc_system *, unsigned short);
static void op_add_hl_bc(gbc_system *);
static void op_ld_a_bcp(gbc_system *);
static void op_dec_bc(gbc_system *);
static void op_inc_c(gbc_system *);
static void op_dec_c(gbc_system *);
static void op_ld_c_d8(gbc_system *, unsigned char);
static void op_rrca(gbc_system *);
static void op_stop_0(gbc_system *, unsigned char);
static void op_ld_de_d16(gbc_system *, unsigned short);
static void op_ld_dep_a(gbc_system *);
static void op_inc_de(gbc_system *);
static void op_inc_d(gbc_system *);
static void op_dec_d(gbc_system *);
static void op_ld_d_d8(gbc_system *, unsigned char);
static void op_rla(gbc_system *);
static void op_jr_r8(gbc_system *, char);
static void op_add_hl_de(gbc_system *);
static void op_ld_a_dep(gbc_system *);
static void op_dec_de(gbc_system *);
static void op_inc_e(gbc_system *);
static void op_dec_e(gbc_system *);
static void op_ld_e_d8(gbc_system *, unsigned char);
static void op_rra(gbc_system *);
static void op_jr_nz_r8(gbc_system *, char);
static void op_ld_hl_d16(gbc_system *, unsigned short);
static void op_ld_hlpp_a(gbc_system *);
static void op_inc_hl(gbc_system *);
static void op_inc_h(gbc_system *);
static void op_dec_h(gbc_system *);
static void op_ld_h_d8(gbc_system *, unsigned char);
static void op_daa(gbc_system *);
static void op_jr_z_r8(gbc_system *, char);
static void op_add_hl_hl(gbc_system *);
static void op_ld_a_hlpp(gbc_system *);
static void op_dec_hl(gbc_system *);
static void op_inc_l(gbc_system *);
static void op_dec_l(gbc_system *);
static void op_ld_l_d8(gbc_system *, unsigned char);
static void op_cpl(gbc_system *);
static void op_jr_nc_r8(gbc_system *, char);
static void op_ld_sp_d16(gbc_system *, unsigned short);
static void op_ld_hlmp_a(gbc_system *);
static void op_inc_sp(gbc_system *);
static void op_inc_hlp(gbc_system *);
static void op_dec_hlp(gbc_system *);
static void op_ld_hlp_d8(gbc_system *, unsigned char);
static void op_scf(gbc_system *);
static void op_jr_c_r8(gbc_system *, char);
static void op_add_hl_sp(gbc_system *);
static void op_ld_a_hlmp(gbc_system *);
static void op_dec_sp(gbc_system *);
static void op_inc_a(gbc_system *);
static void op_dec_a(gbc_system *);
static void op_ld_a_d8(gbc_system *, unsigned char);
static void op_ccf(gbc_system *);
static void op_ld_b_b(gbc_system *);
static void op_ld_b_c(gbc_system *);
static void op_ld_b_d(gbc_system *);
static void op_ld_b_e(gbc_system *);
static void op_ld_b_h(gbc_system *);
static void op_ld_b_l(gbc_system *);
static void op_ld_b_hlp(gbc_system *);
static void op_ld_b_a(gbc_system *);
static void op_ld_c_b(gbc_system *);
static void op_ld_c_c(gbc_system *);
static void op_ld_c_d(gbc_system *);
static void op_ld_c_e(gbc_system *);
static void op_ld_c_h(gbc_system *);
static void op_ld_c_l(gbc_system *);
static void op_ld_c_hlp(gbc_system *);
static void op_ld_c_a(gbc_system *);
static void op_ld_d_b(gbc_system *);
static void op_ld_d_c(gbc_system *);
static void op_ld_d_d(gbc_system *);
static void op_ld_d_e(gbc_system *);
static void op_ld_d_h(gbc_system *);
static void op_ld_d_l(gbc_system *);
static void op_ld_d_hlp(gbc_system *);
static void op_ld_d_a(gbc_system *);
static void op_ld_e_b(gbc_system *);
static void op_ld_e_c(gbc_system *);
static void op_ld_e_d(gbc_system *);
static void op_ld_e_e(gbc_system *);
static void op_ld_e_h(gbc_system *);
static void op_ld_e_l(gbc_system *);
static void op_ld_e_hlp(gbc_system *);
static void op_ld_e_a(gbc_system *);
static void op_ld_h_b(gbc_system *);
static void op_ld_h_c(gbc_system *);
static void op_ld_h_d(gbc_system *);
static void op_ld_h_e(gbc_system *);
static void op_ld_h_h(gbc_system *);
static void op_ld_h_l(gbc_system *);
static void op_ld_h_hlp(gbc_system *);
static void op_ld_h_a(gbc_system *);
static void op_ld_l_b(gbc_system *);
static void op_ld_l_c(gbc_system *);
static void op_ld_l_d(gbc_system *);
static void op_ld_l_e(gbc_system *);
static void op_ld_l_h(gbc_system *);
static void op_ld_l_l(gbc_system *);
static void op_ld_l_hlp(gbc_system *);
static void op_ld_l_a(gbc_system *);
static void op_ld_hlp_b(gbc_system *);
static void op_ld_hlp_c(gbc_system *);
static void op_ld_hlp_d(gbc_system *);
static void op_ld_hlp_e(gbc_system *);
static void op_ld_hlp_h(gbc_system *);
static void op_ld_hlp_l(gbc_system *);
static void op_halt(gbc_system *);
static void op_ld_hlp_a(gbc_system *);
static void op_ld_a_b(gbc_system *);
static void op_ld_a_c(gbc_system *);
static void op_ld_bc_d16(gbc_system *, unsigned short);
static void op_ld_a_e(gbc_system *);
static void op_ld_a_h(gbc_system *);
static void op_ld_a_l(gbc_system *);
static void op_ld_a_hlp(gbc_system *);
static void op_ld_a_a(gbc_system *);
static void op_add_a_b(gbc_system *);
static void op_add_a_c(gbc_system *);
static void op_add_a_d(gbc_system *);
static void op_add_a_e(gbc_system *);
static void op_add_a_h(gbc_system *);
static void op_add_a_l(gbc_system *);
static void op_add_a_hlp(gbc_system *);
static void op_add_a_a(gbc_system *);
static void op_adc_a_b(gbc_system *);
static void op_adc_a_c(gbc_system *);
static void op_adc_a_d(gbc_system *);
static void op_adc_a_e(gbc_system *);
static void op_adc_a_h(gbc_system *);
static void op_adc_a_l(gbc_system *);
static void op_adc_a_hlp(gbc_system *);
static void op_adc_a_a(gbc_system *);
static void op_sub_b(gbc_system *);
static void op_sub_c(gbc_system *);
static void op_sub_d(gbc_system *);
static void op_sub_e(gbc_system *);
static void op_sub_h(gbc_system *);
static void op_sub_l(gbc_system *);
static void op_sub_hlp(gbc_system *);
static void op_sub_a(gbc_system *);
static void op_sbc_a_b(gbc_system *);
static void op_sbc_a_c(gbc_system *);
static void op_sbc_a_d(gbc_system *);
static void op_sbc_a_e(gbc_system *);
static void op_sbc_a_h(gbc_system *);
static void op_sbc_a_l(gbc_system *);
static void op_sbc_a_hlp(gbc_system *);
static void op_sbc_a_a(gbc_system *);
static void op_and_b(gbc_system *);
static void op_and_c(gbc_system *);
static void op_and_d(gbc_system *);
static void op_and_e(gbc_system *);
static void op_and_h(gbc_system *);
static void op_and_l(gbc_system *);
static void op_and_hlp(gbc_system *);
static void op_and_a(gbc_system *);
static void op_xor_b(gbc_system *);
static void op_xor_c(gbc_system *);
static void op_xor_d(gbc_system *);
static void op_xor_e(gbc_system *);
static void op_xor_h(gbc_system *);
static void op_xor_l(gbc_system *);
static void op_xor_hlp(gbc_system *);
static void op_xor_a(gbc_system *);
static void op_or_b(gbc_system *);
static void op_or_c(gbc_system *);
static void op_or_d(gbc_system *);
static void op_or_e(gbc_system *);
static void op_or_h(gbc_system *);
static void op_or_l(gbc_system *);
static void op_or_hlp(gbc_system *);
static void op_or_a(gbc_system *);
static void op_cp_b(gbc_system *);
static void op_cp_c(gbc_system *);
static void op_cp_d(gbc_system *);
static void op_cp_e(gbc_system *);
static void op_cp_h(gbc_system *);
static void op_cp_l(gbc_system *);
static void op_cp_hlp(gbc_system *);
static void op_cp_a(gbc_system *);
static void op_ret_nz(gbc_system *);
static void op_pop_bc(gbc_system *);
static void op_jp_nz_a16(gbc_system *, unsigned short);
static void op_jp_a16(gbc_system *, unsigned short);
static void op_call_nz_a16(gbc_system *, unsigned short);
static void op_push_bc(gbc_system *);
static void op_add_a_d8(gbc_system *, unsigned char);
static void op_rst_00h(gbc_system *);
static void op_ret_z(gbc_system *);
static void op_ret(gbc_system *);
static void op_jp_z_a16(gbc_system *, unsigned short);
static void op_prefix_cb(gbc_system *);
static void op_call_z_a16(gbc_system *, unsigned short);
static void op_call_a16(gbc_system *, unsigned short);
static void op_adc_a_d8(gbc_system *, unsigned char);
static void op_rst_08h(gbc_system *);
static void op_ret_nc(gbc_system *);
static void op_pop_de(gbc_system *);
static void op_jp_nc_a16(gbc_system *, unsigned short);
static void op_call_nc_a16(gbc_system *, unsigned short);
static void op_push_de(gbc_system *);
static void op_sub_d8(gbc_system *, unsigned char);
static void op_rst_10h(gbc_system *);
static void op_ret_c(gbc_system *);
static void op_reti(gbc_system *);
static void op_jp_c_a16(gbc_system *, unsigned short);
static void op_call_c_a16(gbc_system *, unsigned short);
static void op_sbc_a_d8(gbc_system *, unsigned char);
static void op_rst_18h(gbc_system *);
static void op_ldh_a8p_a(gbc_system *, unsigned char);
static void op_pop_hl(gbc_system *);
static void op_ld_cp_a(gbc_system *, unsigned char);
static void op_push_hl(gbc_system *);
static void op_and_d8(gbc_system *, unsigned char);
static void op_rst_20h(gbc_system *);
static void op_add_sp_r8(gbc_system *, char);
static void op_jp_hlp(gbc_system *);
static void op_ld_a16p_a(gbc_system *, unsigned short);
static void op_xor_d8(gbc_system *, unsigned char);
static void op_rst_28h(gbc_system *);
static void op_ldh_a_a8p(gbc_system *, unsigned char);
static void op_pop_af(gbc_system *);
static void op_ld_a_cp(gbc_system *, unsigned char);
static void op_di(gbc_system *);
static void op_push_af(gbc_system *);
static void op_or_d8(gbc_system *, unsigned char);
static void op_rst_30h(gbc_system *);
static void op_ld_hl_sppr8(gbc_system *, char);
static void op_ld_sp_hl(gbc_system *);
static void op_ld_a_a16p(gbc_system *, unsigned short);
static void op_ei(gbc_system *);
static void op_cp_d8(gbc_system *, unsigned char);
static void op_rst_38h(gbc_system *);
static void op_res_0_b(gbc_system *);
static void op_rlc_b(gbc_system *);
static void op_rlc_d(gbc_system *);
static void op_rlc_e(gbc_system *);
static void op_rlc_h(gbc_system *);
static void op_rlc_l(gbc_system *);
static void op_rlc_hlp(gbc_system *);
static void op_rlc_a(gbc_system *);
static void op_rrc_b(gbc_system *);
static void op_rrc_c(gbc_system *);
static void op_rrc_d(gbc_system *);
static void op_rrc_e(gbc_system *);
static void op_rrc_h(gbc_system *);
static void op_rrc_l(gbc_system *);
static void op_rrc_hlp(gbc_system *);
static void op_rrc_a(gbc_system *);
static void op_rl_b(gbc_system *);
static void op_rl_c(gbc_system *);
static void op_rl_d(gbc_system *);
static void op_rl_e(gbc_system *);
static void op_rl_h(gbc_system *);
static void op_rl_l(gbc_system *);
static void op_rl_hlp(gbc_system *);
static void op_rl_a(gbc_system *);
static void op_rr_b(gbc_system *);
static void op_rr_c(gbc_system *);
static void op_rr_d(gbc_system *);
static void op_rr_e(gbc_system *);
static void op_rr_h(gbc_system *);
static void op_rr_l(gbc_system *);
static void op_rr_hlp(gbc_system *);
static void op_rr_a(gbc_system *);
static void op_sla_b(gbc_system *);
static void op_sla_c(gbc_system *);
static void op_sla_d(gbc_system *);
static void op_sla_e(gbc_system *);
static void op_sla_h(gbc_system *);
static void op_sla_l(gbc_system *);
static void op_sla_hlp(gbc_system *);
static void op_sla_a(gbc_system *);
static void op_sra_b(gbc_system *);
static void op_sra_c(gbc_system *);
static void op_sra_d(gbc_system *);
static void op_sra_e(gbc_system *);
static void op_sra_h(gbc_system *);
static void op_sra_l(gbc_system *);
static void op_sra_hlp(gbc_system *);
static void op_sra_a(gbc_system *);
static void op_swap_b(gbc_system *);
static void op_swap_c(gbc_system *);
static void op_swap_d(gbc_system *);
static void op_swap_e(gbc_system *);
static void op_swap_h(gbc_system *);
static void op_swap_l(gbc_system *);
static void op_swap_hlp(gbc_system *);
static void op_swap_a(gbc_system *);
static void op_srl_b(gbc_system *);
static void op_srl_c(gbc_system *);
static void op_srl_d(gbc_system *);
static void op_srl_e(gbc_system *);
static void op_srl_h(gbc_system *);
static void op_srl_l(gbc_system *);
static void op_srl_hlp(gbc_system *);
static void op_srl_a(gbc_system *);
static void op_bit_0_b(gbc_system *);
static void op_bit_0_c(gbc_system *);
static void op_bit_0_d(gbc_system *);
static void op_bit_0_e(gbc_system *);
static void op_bit_0_h(gbc_system *);
static void op_bit_0_l(gbc_system *);
static void op_bit_0_hlp(gbc_system *);
static void op_bit_0_a(gbc_system *);
static void op_bit_1_b(gbc_system *);
static void op_bit_1_c(gbc_system *);
static void op_bit_1_d(gbc_system *);
static void op_bit_1_e(gbc_system *);
static void op_bit_1_h(gbc_system *);
static void op_bit_1_l(gbc_system *);
static void op_bit_1_hlp(gbc_system *);
static void op_bit_1_a(gbc_system *);
static void op_bit_2_b(gbc_system *);
static void op_bit_2_c(gbc_system *);
static void op_bit_2_d(gbc_system *);
static void op_bit_2_e(gbc_system *);
static void op_bit_2_h(gbc_system *);
static void op_bit_2_l(gbc_system *);
static void op_bit_2_hlp(gbc_system *);
static void op_bit_2_a(gbc_system *);
static void op_bit_3_b(gbc_system *);
static void op_bit_3_c(gbc_system *);
static void op_bit_3_d(gbc_system *);
static void op_bit_3_e(gbc_system *);
static void op_bit_3_h(gbc_system *);
static void op_bit_3_l(gbc_system *);
static void op_bit_3_hlp(gbc_system *);
static void op_bit_3_a(gbc_system *);
static void op_bit_4_b(gbc_system *);
static void op_bit_4_c(gbc_system *);
static void op_bit_4_d(gbc_system *);
static void op_bit_4_e(gbc_system *);
static void op_bit_4_h(gbc_system *);
static void op_bit_4_l(gbc_system *);
static void op_bit_4_hlp(gbc_system *);
static void op_bit_4_a(gbc_system *);
static void op_bit_5_b(gbc_system *);
static void op_bit_5_c(gbc_system *);
static void op_bit_5_d(gbc_system *);
static void op_bit_5_e(gbc_system *);
static void op_bit_5_h(gbc_system *);
static void op_bit_5_l(gbc_system *);
static void op_bit_5_hlp(gbc_system *);
static void op_bit_5_a(gbc_system *);
static void op_bit_6_b(gbc_system *);
static void op_bit_6_c(gbc_system *);
static void op_bit_6_d(gbc_system *);
static void op_bit_6_e(gbc_system *);
static void op_bit_6_h(gbc_system *);
static void op_bit_6_l(gbc_system *);
static void op_bit_6_hlp(gbc_system *);
static void op_bit_6_a(gbc_system *);
static void op_bit_7_b(gbc_system *);
static void op_bit_7_c(gbc_system *);
static void op_bit_7_d(gbc_system *);
static void op_bit_7_e(gbc_system *);
static void op_bit_7_h(gbc_system *);
static void op_bit_7_l(gbc_system *);
static void op_bit_7_hlp(gbc_system *);
static void op_bit_7_a(gbc_system *);
static void op_rlc_c(gbc_system *);
static void op_res_0_c(gbc_system *);
static void op_res_0_d(gbc_system *);
static void op_res_0_e(gbc_system *);
static void op_res_0_h(gbc_system *);
static void op_res_0_l(gbc_system *);
static void op_res_0_hlp(gbc_system *);
static void op_res_0_a(gbc_system *);
static void op_res_1_b(gbc_system *);
static void op_res_1_c(gbc_system *);
static void op_res_1_d(gbc_system *);
static void op_res_1_e(gbc_system *);
static void op_res_1_h(gbc_system *);
static void op_res_1_l(gbc_system *);
static void op_res_1_hlp(gbc_system *);
static void op_res_1_a(gbc_system *);
static void op_res_2_b(gbc_system *);
static void op_res_2_c(gbc_system *);
static void op_res_2_d(gbc_system *);
static void op_res_2_e(gbc_system *);
static void op_res_2_h(gbc_system *);
static void op_res_2_l(gbc_system *);
static void op_res_2_hlp(gbc_system *);
static void op_res_2_a(gbc_system *);
static void op_res_3_b(gbc_system *);
static void op_res_3_c(gbc_system *);
static void op_res_3_d(gbc_system *);
static void op_res_3_e(gbc_system *);
static void op_res_3_h(gbc_system *);
static void op_res_3_l(gbc_system *);
static void op_res_3_hlp(gbc_system *);
static void op_res_3_a(gbc_system *);
static void op_res_4_b(gbc_system *);
static void op_res_4_c(gbc_system *);
static void op_res_4_d(gbc_system *);
static void op_res_4_e(gbc_system *);
static void op_res_4_h(gbc_system *);
static void op_res_4_l(gbc_system *);
static void op_res_4_hlp(gbc_system *);
static void op_res_4_a(gbc_system *);
static void op_res_5_b(gbc_system *);
static void op_res_5_c(gbc_system *);
static void op_res_5_d(gbc_system *);
static void op_res_5_e(gbc_system *);
static void op_res_5_h(gbc_system *);
static void op_res_5_l(gbc_system *);
static void op_res_5_hlp(gbc_system *);
static void op_res_5_a(gbc_system *);
static void op_res_6_b(gbc_system *);
static void op_res_6_c(gbc_system *);
static void op_res_6_d(gbc_system *);
static void op_res_6_e(gbc_system *);
static void op_res_6_h(gbc_system *);
static void op_res_6_l(gbc_system *);
static void op_res_6_hlp(gbc_system *);
static void op_res_6_a(gbc_system *);
static void op_res_7_b(gbc_system *);
static void op_res_7_c(gbc_system *);
static void op_res_7_d(gbc_system *);
static void op_res_7_e(gbc_system *);
static void op_res_7_h(gbc_system *);
static void op_res_7_l(gbc_system *);
static void op_res_7_hlp(gbc_system *);
static void op_res_7_a(gbc_system *);
static void op_set_0_b(gbc_system *);
static void op_set_0_c(gbc_system *);
static void op_set_0_d(gbc_system *);
static void op_set_0_e(gbc_system *);
static void op_set_0_h(gbc_system *);
static void op_set_0_l(gbc_system *);
static void op_set_0_hlp(gbc_system *);
static void op_set_0_a(gbc_system *);
static void op_set_1_b(gbc_system *);
static void op_set_1_c(gbc_system *);
static void op_set_1_d(gbc_system *);
static void op_set_1_e(gbc_system *);
static void op_set_1_h(gbc_system *);
static void op_set_1_l(gbc_system *);
static void op_set_1_hlp(gbc_system *);
static void op_set_1_a(gbc_system *);
static void op_set_2_b(gbc_system *);
static void op_set_2_c(gbc_system *);
static void op_set_2_d(gbc_system *);
static void op_set_2_e(gbc_system *);
static void op_set_2_h(gbc_system *);
static void op_set_2_l(gbc_system *);
static void op_set_2_hlp(gbc_system *);
static void op_set_2_a(gbc_system *);
static void op_set_3_b(gbc_system *);
static void op_set_3_c(gbc_system *);
static void op_set_3_d(gbc_system *);
static void op_set_3_e(gbc_system *);
static void op_set_3_h(gbc_system *);
static void op_set_3_l(gbc_system *);
static void op_set_3_hlp(gbc_system *);
static void op_set_3_a(gbc_system *);
static void op_set_4_b(gbc_system *);
static void op_set_4_c(gbc_system *);
static void op_set_4_d(gbc_system *);
static void op_set_4_e(gbc_system *);
static void op_set_4_h(gbc_system *);
static void op_set_4_l(gbc_system *);
static void op_set_4_hlp(gbc_system *);
static void op_set_4_a(gbc_system *);
static void op_set_5_b(gbc_system *);
static void op_set_5_c(gbc_system *);
static void op_set_5_d(gbc_system *);
static void op_set_5_e(gbc_system *);
static void op_set_5_h(gbc_system *);
static void op_set_5_l(gbc_system *);
static void op_set_5_hlp(gbc_system *);
static void op_set_5_a(gbc_system *);
static void op_set_6_b(gbc_system *);
static void op_set_6_c(gbc_system *);
static void op_set_6_d(gbc_system *);
static void op_set_6_e(gbc_system *);
static void op_set_6_h(gbc_system *);
static void op_set_6_l(gbc_system *);
static void op_set_6_hlp(gbc_system *);
static void op_set_6_a(gbc_system *);
static void op_set_7_b(gbc_system *);
static void op_set_7_c(gbc_system *);
static void op_set_7_d(gbc_system *);
static void op_set_7_e(gbc_system *);
static void op_set_7_h(gbc_system *);
static void op_set_7_l(gbc_system *);
static void op_set_7_hlp(gbc_system *);
static void op_set_7_a(gbc_system *);


